apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: production
namespace: financeiro
commonAnnotations:
  note: Ambiente de Produção
resources:
  - ../../base

patches:
  - path: deploy_patch.json
    target:
      kind: Deployment
      labelSelector: app=email-services

patchesStrategicMerge:
  - production-configMap.yaml

