package fieg.externos.compartilhadoservice.acesso;

public enum Acessos {

    SECRETARIA_CONTRATO(455, "Secretaria / Contrato"),
    TESOURARIA(456, "Tesouraria"),
    BANCOS(457, "Bancos"),
    AGENCIAS(458, "Agências"),
    CONTAS_CORRENTES(459, "Contas Correntes"),
    CONVENIOS_BANCARIOS(460, "Convênios Bancários"),
    EFETUAR_RECEBIMENTO(461, "Efetuar Recebimento"),
    MOVIMENTO_DIARIO(462, "Movimento Diário"),
    RETIRAR_MULTAS_E_JUROS(464, "Retirar Multas e Juros"),
    CANCELAR_COBRANCA(465, "Cancelar Cobrança"),
    DESATIVAR_COBRANCA(466, "Desativar Cobrança"),
    RETORNO_DO_BANCO(471, "Retorno do Banco"),
    GERAR_COBRANCA_DE_CONTRATOS(472, "Gerar Cobrança de Contratos"),
    IMPRIMIR_BOLETO(473, "Imprimir Boleto"),
    PROMOCAO(486, "Promoção"),
    CONCEDER_PROMOCAO(487, "Conceder Promoção"),
    CONFIGURACAO_DO_BANCO_DE_DADOS(488, "Configuração do Banco de Dados"),
    MOTIVO_DE_CANCELAMENTO_DA_COBRANCA(496, "Motivo de Cancelamento da Cobrança"),
    DEVOLUCAO_NUMERARIA(498, "Devolução Numerária"),
    PESSOAS(551, "Pessoas"),
    PRODUTO_SERVICO_AVULSO(553, "Produto/Serviço Avulso"),
    DESATIVAR_PRODUTO_SERVICO_AVULSO(554, "Desativar produto/serviço avulso"),
    GERAR_COBRANCA_DE_SERVICOS_PRODUTOS_AVULSOS(559, "Gerar cobrança de serviços/produtos avulsos"),
    ESTORNAR_COBRANCA(595, "Estornar cobrança"),
    RELATORIO_MOVIMENTO_DIARIO(601, "Relatório movimento diário"),
    RELATORIO_RECEBIMENTOS_POR_EVENTO(602, "Relatório recebimentos por evento"),
    RELATORIO_DE_COBRANCAS_EM_ABERTO(603, "Relatório de cobranças em aberto"),
    RELATORIO_DE_COBRANCAS_VENCIDAS(604, "Relatório de cobranças vencidas"),
    RELATORIO_DE_COBRANCAS_ESTORNADAS(605, "Relatório de cobranças estornadas"),
    RELATORIO_DE_PROMOCOES_CONCEDIDAS(606, "Relatório de promoções concedidas"),
    RELATORIO_DE_COBRANCAS_POR_CENTRO_DE_RESP(607, "Relatório de cobranças por centro de resp."),
    RELATORIO_DE_RETIRADAS_DE_MULTAS_E_JUROS(608, "Relatório de retiradas de multas e juros"),
    RELATORIO_DE_DEVOLUCAO_NUMERARIA(609, "Relatório de devolução numerária"),
    RELATORIO_DE_COBRANCAS_NAO_ADM_CR5(617, "Relatório de cobranças Não Adm CR5"),
    RELATORIO_DE_COBRANCAS_CANCELADAS(618, "Relatório de cobranças Canceladas"),
    SECRETARIA_PRODUTO_AVULSO(633, "Secretaria \\ Produto Avulso"),
    GERAR_CONTRATOS_AVULSOS(637, "Gerar contratos avulsos"),
    GERAR_COBRANCA_DE_CONTRATOS_NAO_ADMINISTRADOS_CR5(644, "Gerar Cobrança de contratos não administrados CR5"),
    CANCELAR_CONTRATO_PRODUTO_AVULSO(646, "Cancelar Contrato Produto Avulso"),
    AGRUPAR_PARCELAS(746, "Agrupar parcelas"),
    CANCELAMENTO_DE_BOLETOS(748, "Cancelamento de boletos"),
    RELATORIO_DEMONSTRATIVO_DE_COBRANCAS_EM_ABERTO(755, "Relatório Demonstrativo de cobrancas em aberto"),
    ALTERAR_DESCONTO_ANTES_DO_VENCIMENTO_NO_BOLETO(773, "Alterar Desconto antes do vencimento no boleto"),
    RELATORIO_DE_SALDO_CONTRATUAL_POR_PERIODO(774, "Relatório de saldo contratual por periodo"),
    RELATORIO_DE_CONTRATOS_ABERTOS(775, "Relatório de Contratos Abertos"),
    RELATORIO_DE_CONTRATOS_CANCELADOS(776, "Relatório de Contratos Cancelados"),
    RELATORIO_DE_CONTRATOS_A_CANCELAR(777, "Relatório de Contratos À Cancelar"),
    RELATORIO_DE_CONTRATOS_COBRADOS(778, "Relatório de Contratos Cobrados"),
    RELATORIO_DE_SALDO_POR_UNIDADE(779, "Relatório de Saldo por unidade"),
    RELATORIO_DE_BOLETOS_CANCELADOS_BAIXADOS(780, "Relatório de Boletos Cancelados Baixados"),
    CANCELAR_COBRANCAS_DO_CONTRATO(789, "Cancelar cobrancas do contrato"),
    RELATORIO_DE_SALDO_POR_PRODUTO(799, "Relatório de Saldo por Produto"),
    PRODUTO_CONTA_CONTABIL(816, "Produto Conta Contabil"),
    RELATORIO_DE_COBRANCAS_PAGAS_E_A_RECEBER(821, "Relatório de Cobranças Pagas e A Receber"),
    EXPORTAR_CADIN(827, "Exportar Cadin"),
    MUDAR_STATUS_ADM_CADIN(937, "Mudar Status Adm. Cadin"),
    RELATORIOD_DE_COBRANCAS_EXPORTADAS_CADIN(938, "Relatóriod de Cobranças exportadas Cadin"),
    CANCELAMENTO_DE_PAGAMENTO(998, "Cancelamento de pagamento"),
    DESCANCELAR_COBRANCAS(1011, "Descancelar Cobranças"),
    SUBSTITUICAO_DE_CONTRATOS(1046, "Substituição de Contratos"),
    EXTINCAO_DE_CONTRATOS(1047, "Extinção de Contratos"),
    VISUALIZAR_SITUACAO_DO_CLIENTE(1048, "Visualizar situação do cliente"),
    FAZER_LOGOFF_NO_SISTEMA(1097, "Fazer logoff no sistema"),
    DEPARA_PRODUTO_CONTA_CONTABIL(1129, "Depara Produto Conta Contabil"),
    INATIVAR_PRODUTO_CONTA_CONTABIL(1130, "Inativar Produto conta contabil"),
    INFORMAR_NUMERO_E_DATA_DE_EMISSAO_NOTA_FISCAL(1158, "Informar Número e data de emissão nota fiscal"),
    CANCELAR_PAGAMENTO_DEPOIS_DO_DIA_DE_RECEBIMENTO(1159, "Cancelar pagamento depois do dia de recebimento"),
    REALIZAR_RATEIO_DO_FINANCIAMENTO_EDUCACIONAL(1174, "Realizar Rateio do financiamento educacional"),
    BAIXAR_FINANCIAMENTO_EDUCACIONAL(1272, "Baixar Financiamento Educacional"),
    RELATORIO_DE_POSICAO_FINANCEIRA(1307, "Relatório de posição financeira"),
    IMPOSTOS(1321, "Impostos"),
    RELATORIO_DE_DESCONTOS(1323, "Relatório de descontos"),
    RELATORIO_ESTATISTICO_DE_BOLETOS_POR_CENTRO_E_CONT(1329, "Relatório estatístico de boletos por centro e cont"),
    VERIFICA_ARQUIVO_DE_RETORNO_DETALHES(1406, "Verifica arquivo de retorno detalhes"),
    AUDITORIA(1413, "Auditoria"),
    ADMINISTRADOR_CR5(1429, "Administrador CR5"),
    RELATORIOS_GRAFICOS(1540, "Relatórios Gráficos"),
    CONCESSAO_DE_DESCONTO(1680, "Concessão de Desconto"),
    ESTORNAR_PARCELA_PARA_CONTRATO_COBRADO(1743, "Estornar parcela para contrato COBRADO"),
    CORRIGIR_CONVENIO_DE_PARCELA(1745, "Corrigir convênio de parcela"),
    DESC_ESPECIAL_PARA_EMPRESA_ASSOCIADA_A_SINDICATO(1754, "Desc. Especial para Empresa Associada a Sindicato"),
    DEPARA(1755, "DePara"),
    VISUALIZAR_GRAFICO_DE_PAGO_A_MENOR(1774, "Visualizar Gráfico de Pago a Menor"),
    OLYMPIA_CONCEDE_DESC_PARA_CATEIRA_SOCIAL(1775, "Olympia - Concede desc. para Cateira Social"),
    NEGOCIACAO_CIN(1777, "Negociação CIN"),
    CADASTRO_DE_IMPRESSORAS(1792, "Cadastro de impressoras"),
    GERAR_REMESSA_CNBA_240(1793, "Gerar remessa CNBA 240"),
    GERAR_REMESSA_DE_SMS(1797, "Gerar Remessa de SMS"),
    VISUALIZAR_DASHBOARD(1813, "Visualizar Dashboard"),
    GERACAO_DE_COBRANCAS_EM_LOTE(1816, "Geração de Cobranças em Lote"),
    ADMNISTRADOR_CADIN(1855, "Admnistrador CADIN"),
    EXPORTAR_PARA_CADIN(1858, "Exportar para Cadin"),
    CANCELAR_CONTRATO_NO_7o_DIA_APOS_VENCIMENTO(1860, "Cancelar contrato no 7º dia após vencimento"),
    TERMINAIS_TEF(1864, "Terminais TEF"),
    DESCONTO_COVID(1866, "Desconto covid"),
    INFORMACOES_ECOMMERCE(1868, "Informações E-commerce"),
    ALTERAR_DATA_DE_ESTORNO(1869, "Alterar data de estorno"),
    TEF_ESTORNO(1870, "TEF Estorno"),
    MUDAR_STATUS_CONTRATO_E_PARCELAS(1872, "Mudar status Contrato e Parcelas"),
    ADMINISTRAR_FINANCIAMENTO(1873, "Administrar Financiamento"),
    MUDAR_DATA_DE_VIGENCIA_DA_COBRANCA(1874, "Mudar Data de Vigência da Cobrança"),
    DESVINCULAR_RESPONSAVEL_FINANCEIRO(1875, "Desvincular Responsável Financeiro"),
    ALTERAR_PORCENTAGEM_DO_ESTORNO_DA_MULTA_RESCISORIA(1876, "Alterar Porcentagem do Estorno da Multa Rescisoria"),
    ALTERAR_O_NOME_OU_RAZAO_SOCIAL_DO_CLIENTE(1877, "Alterar o nome ou razão social do cliente"),
    CANCELAR_CONTRATO(1880, "Cancelar Contrato"),
    BAIXA_PROTHEUS(1882, "Baixa Protheus"),
    CONSULTAR_PIX(1889, "Consultar PIX"),
    ADMINISTRADOR_NOTA_FISCAL(1891, "Administrador Nota Fiscal"),
    CRIACAO_DE_CONTRATO_EM_REDE(1892, "Criação de Contrato em Rede"),
    CONCILIACAO_CR5_X_PROTHEUS(1893, "Conciliação CR5 X Protheus");

    public final int idAcesso;
    public final String nomeAcesso;

    Acessos(int idAcesso, String nomeAcesso) {
        this.idAcesso = idAcesso;
        this.nomeAcesso = nomeAcesso;
    }
}
