commonLabels:
  app: sms-services-v2
  org: fieg
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: compartilhado
