FROM registry.fieg.com.br/arquitetura-software/fieg-jdk:jdk-21

USER root

RUN mkdir -p /app \
   && chown 1001:1001 /app -R

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

COPY --chown=1001 target/quarkus-app /deployments/

EXPOSE 8080
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]
