FROM registry.fieg.com.br/nginx/nginx:1.19-alpine

RUN mkdir -p /usr/share/nginx/html/cr5-web/v2

COPY geapp/src/main/resources/default.conf /etc/nginx/conf.d/default.conf
COPY geapp/src/main/resources/nginx.conf /etc/nginx/nginx.conf

COPY ./dist /usr/share/nginx/html/cr5-web/v2

